<?php

namespace App\Http\Livewire;

use App\Models\Incident_Entry;
use Barryvdh\Debugbar\Facades\Debugbar;
use Mediconesystems\LivewireDatatables\Column;
use Mediconesystems\LivewireDatatables\DateColumn;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;

class IRReportNewEntries extends LivewireDatatable
{
//    public $model = Incident_Entry::class;

public $name = "test999";

    protected $listeners = [
        'refreshLivewireDatatable',
        'addFilter',
    ];


    public function doDateFilterStart($index, $start) {
        Debugbar::info('test');

        $this->activeDateFilters[$index]['start'] = $start;
        $this->setPage(1);
        $this->setSessionStoredFilters();

    }
    public function refreshLivewireDatatable()
    {
        parent::refreshLivewireDatatable(); // TODO: Change the autogenerated stub
    }

    public function updated() {
    }
    public function render() {
        $this->persistFilters = false;
        parent::render();



        return view('datatables::datatable')->layoutData(['title' => $this->title]);

    }

    public function addFilter() {
//        $this->activeSelectFilters[1][0] = "Hayden Kovac";


    }
    public function builder()
    {
//        return User::query();

//        $this->activeSelectFilters[1][0] = "Hayden Kovac";

       return Incident_Entry::query()->with(['get_child', 'get_child.getCaseManageAssignedHome']);


    }

    public $defaultFilters = [
        /*'get_child.initials' => 'Hayden Kovac',*/
//        'get_child.initials' => "Hayden Kovac",
//        'child.initials' => "Hayden Kovac"
    ];

    public function getInitialsProperty()
    {
        return \App\Models\Child::where('WeSchedule','=','0')->pluck('initials');
    }

    public function getFosterHomeProperty() {
        return \App\Models\User::where('user_type','>=','2.0')->where('user_type','<=','3.0')->pluck('name');
    }

    public function getCaseManagerProperty() {
        return \App\Models\User::where('user_type','=','3.4')->pluck('name');
    }
    public function columns()
    {
       return [
           DateColumn::name('created_at')
            ->label('Date Created/Received')
            ->defaultSort('asc')
//            ->searchable()
            ->filterable(),

            Column::name('get_child.initials')
            ->defaultSort('asc')
            ->filterable($this->initials),

           Column::name('get_child.getCaseManageAssignedHome.name')
                ->label('Foster Home')
                ->filterable($this->fosterHome),

//           Column::name('get_child.getCaseManageAssignedHome.fk_CaseManagerID')
//               ->label('Case Manager'),
////               ->filterable($this->CaseManager)

           Column::name('get_child.getCaseManageAssignedHome.id')
               ->label('Case Manager2')


       ];
    }
}
